#!/bin/bash

PROGRAM=vastai_exporter
SYSTEMDFILE=/etc/systemd/system/$PROGRAM.service

if [ ! -f $SYSTEMDFILE ]
then
    echo -n "Enter your Vast.ai API key: "
    read APIKEY
	cat $PROGRAM.service | sed -i "s/CHANGEME/$APIKEY/g" > $SYSTEMDFILE
fi

systemctl enable $PROGRAM
systemctl start $PROGRAM
systemctl status $PROGRAM
